###TODO
### Autosave figures?
### Detailed bouts analysis -> Mean . ZT + Phase

######### Required package ##########
if(!require(tidyr)){install.packages("tidyr")}
if(!require(openxlsx)){install.packages("openxlsx")}
if(!require(ggplot2)){install.packages("ggplot2")}
if(!require(tidyverse)){install.packages("tidyverse")}
#if(!require(MetBrewer)){install.packages("MetBrewer")}


Sleep_analysis = function(file_path){
  
###### Data Import and preparation #####
### Import dataframe generated by importing all .csv files in a given folder
RawData = list.files(path = file_path, pattern = "*.csv", full.names = T) %>% map_df(~read.csv(.))
ID = file_path
#ID = 3086
#ID = gsub("/","_", file_path)

### Separate date and time
RawData = separate(RawData,time_stamp, into = c("date","hour"),sep=" ")
RawData = arrange(RawData, date, hour)
date = unique(RawData$date)

# Base parameters
ZT = seq(0,22, by=2)
wb = createWorkbook()
wb2 = createWorkbook()
State = c("W", "S", "P")


#### Sleep state extraction ####
for (t in date){
  Subfull = subset(RawData, date == t)
  date_ca = rep(t,12)
  df = data.frame(date_ca,ZT) #Reset the dataframe at each loop
  df2 = data.frame(date_ca,ZT)
  for (z in State){
    count_table = c() #reset the array at each loop
    count_table_max = c()
    count_table_mean = c()
    for (y in ZT){
      count <- nrow(Subfull[Subfull$ZT == y & Subfull$rodent_sleep == z,])
      count_table = c(count_table, count)
      
      ### Count of sequential same state
      sub_Subfull = subset(Subfull, ZT == y)
      if (length(sub_Subfull$ZT !=0)){
      r = rle(sub_Subfull$rodent_sleep == z)
      count_ser = r$lengths[r$values == TRUE]
      max_count = max(count_ser)
      ave_count = mean(count_ser)
      } else {
        max_count = NA
        ave_count = NA
      }

      ### Combine all ZT
      count_table_max = c(count_table_max, max_count)
      count_table_mean = c(count_table_mean, ave_count)
    }
    df = cbind(df, count_table)
    df2 = cbind(df2, count_table_max,count_table_mean)
  }
  
  names(df)=c("Date","ZT", "Wake", "Sleep", "Paradoxical")
  names(df2)=c("Date","ZT", "Wake_max", "Wake_ave", "Sleep_max", "Sleep_ave",
               "Paradoxical_max", "Paradoxical_ave")
  
  ### Create sum and percentage columns
  df$Sum = df$Wake + df$Sleep + df$Paradoxical
  df$Wake_percent = df$Wake / df$Sum * 100
  df$Sleep_percent = df$Sleep / df$Sum * 100
  df$Paradoxical_percent = df$Paradoxical / df$Sum * 100
  
  ### Create dataframe for summary of state per phase
  Phase = c(rep("Light",3),rep("Dark",3))
  Stage_sleep = rep(c("Wake","Sleep","Paradoxical"),2)
  Sum_Phase = c(sum(df[1:6,3]),sum(df[1:6,4]),sum(df[1:6,5]),sum(df[7:12,3]),
                sum(df[7:12,4]),sum(df[7:12,5]))
  df_sum = data.frame(Phase, Stage_sleep,Sum_Phase)
  
  Mean_Phase = c(mean(df[1:6,3]),mean(df[1:6,4]),mean(df[1:6,5]),mean(df[7:12,3]),
                 mean(df[7:12,4]),mean(df[7:12,5]))
  df_mean = data.frame(Phase, Stage_sleep, Mean_Phase)

  ### add data to workbook
  addWorksheet(wb, t)
  writeData(wb, sheet= t, x = df)
  
  alt_title = paste0(t,"-summary")
  addWorksheet(wb, alt_title)
  writeData(wb, sheet = alt_title, x=df_sum)
  
  df2_name = paste0(t,"-bouts")
  addWorksheet(wb,df2_name)
  writeData(wb, sheet = df2_name, x= df2)
}

### Combine all days
df_one = data.frame()
for (t in date){
  temp = read.xlsx(wb, sheet=t)
  df_one = rbind(df_one,temp)
}
x = seq(1, length(df_one$Wake/length(df_one)))
h = seq(0, length(df_one$ZT), by=12)
df_one = cbind(df_one,x)
df_one = df_one[df_one$Sum != 0,]

df2_one = data.frame()
for (t in date){
  df2_name = paste0(t,"-bouts")
  temp2 = read.xlsx(wb, sheet=df2_name)
  df2_one = rbind(df2_one,temp2)
}

x2 = seq(1, length(df2_one$Wake_max/length(df2_one)))
df2_one = cbind(df2_one,x2)
df2_one = na.omit(df2_one)

### Create dataframe for summary of state per phase
Phase = c(rep("Light",3),rep("Dark",3))
Stage_sleep = rep(c("Wake","Sleep","Paradoxical"),2)

Mean_Phase_one = c(mean(df_one$Wake[df_one$ZT < 12]),mean(df_one$Sleep[df_one$ZT < 12]),mean(df_one$Paradoxical[df_one$ZT < 12]),
                   mean(df_one$Wake[df_one$ZT >= 12]),mean(df_one$Sleep[df_one$ZT >= 12]),mean(df_one$Paradoxical[df_one$ZT >= 12]))

SD_Phase_one = c(sd(df_one$Wake[df_one$ZT < 12]),
                  sd(df_one$Sleep[df_one$ZT < 12]),
                  sd(df_one$Paradoxical[df_one$ZT < 12]),
                  sd(df_one$Wake[df_one$ZT >= 12]),
                  sd(df_one$Sleep[df_one$ZT >= 12]),
                  sd(df_one$Paradoxical[df_one$ZT >= 12])
                  )
n_phase_one = c(length(df_one$Wake[df_one$ZT < 12]),
                length(df_one$Sleep[df_one$ZT < 12]),
                length(df_one$Paradoxical[df_one$ZT < 12]),
                length(df_one$Wake[df_one$ZT >= 12]),
                length(df_one$Sleep[df_one$ZT >= 12]),
                length(df_one$Paradoxical[df_one$ZT >= 12])
)

df_mean_one = data.frame(Phase, Stage_sleep, Mean_Phase_one, SD_Phase_one, n_phase_one)

date_phase= c(date,date)
date_phase = sort(date_phase)
Phase_day = rep(c("Light","Dark"),length(date_phase)/2)
df3 = data.frame(date_phase, Phase_day)
df3_gne = data.frame()
temp_df3 = c()

for (t in date){
  Mean_Light_day = c(mean(df_one$Wake[df_one$ZT<12 & df_one$Date ==t]),
                     mean(df_one$Sleep[df_one$ZT<12 & df_one$Date ==t]),
                     mean(df_one$Paradoxical[df_one$ZT<12 & df_one$Date ==t]),
                     sd(df_one$Wake[df_one$ZT<12 & df_one$Date ==t]),
                     sd(df_one$Sleep[df_one$ZT<12 & df_one$Date ==t]),
                     sd(df_one$Paradoxical[df_one$ZT<12 & df_one$Date ==t]),
                     length(df_one$Wake[df_one$ZT<12 & df_one$Date ==t]),
                     length(df_one$Sleep[df_one$ZT<12 & df_one$Date ==t]),
                     length(df_one$Paradoxical[df_one$ZT<12 & df_one$Date ==t]))

  Mean_Dark_day = c(mean(df_one$Wake[df_one$ZT>=12 & df_one$Date ==t]),
                     mean(df_one$Sleep[df_one$ZT>=12 & df_one$Date ==t]),
                     mean(df_one$Paradoxical[df_one$ZT>=12 & df_one$Date ==t]),
                     sd(df_one$Wake[df_one$ZT>=12&df_one$Date ==t]),
                     sd(df_one$Sleep[df_one$ZT>=12&df_one$Date ==t]),
                     sd(df_one$Paradoxical[df_one$ZT>=12&df_one$Date ==t]),
                     length(df_one$Wake[df_one$ZT>=12&df_one$Date ==t]),
                     length(df_one$Sleep[df_one$ZT>=12&df_one$Date ==t]),
                     length(df_one$Paradoxical[df_one$ZT>=12&df_one$Date ==t]))

  temp_df3 = rbind(temp_df3, Mean_Light_day,Mean_Dark_day)
}
df3 = cbind(df3,temp_df3)
names(df3) = c("Date","Phase","Mean_Wake","Mean_Sleep","Mean_Paradoxical","SD_Wake","SD_Sleep","SD_Paradoxical","N_Wake","N_Sleep","N_Paradoxical")
rownames(df3)=NULL
df3 = df3[df3$Mean_Wake !=0,]

df_ZT_Mean = data.frame(ZT)
mean_table = data.frame()
for (y in ZT){
  ZT_mean = c(mean(df_one$Wake[df_one$ZT == y]),mean(df_one$Sleep[df_one$ZT == y]),mean(df_one$Paradoxical[df_one$ZT == y]),
              sd(df_one$Wake[df_one$ZT ==y]),sd(df_one$Sleep[df_one$ZT ==y]),sd(df_one$Paradoxical[df_one$ZT ==y]),
              length(df_one$Wake[df_one$ZT == y]),length(df_one$Sleep[df_one$ZT==y]),length(df_one$Paradoxical[df_one$ZT==y]),
              nrow(RawData[RawData$rodent_sleep == "W" & RawData$ZT == y,])/nrow(RawData[RawData$ZT == 0,])*100,
              nrow(RawData[RawData$rodent_sleep == "S" & RawData$ZT == y,])/nrow(RawData[RawData$ZT == 0,])*100,
              nrow(RawData[RawData$rodent_sleep == "P" & RawData$ZT == y,])/nrow(RawData[RawData$ZT == 0,])*100
              )
  
  mean_table = rbind(mean_table, ZT_mean)
  names(mean_table) = c("Wake","Sleep","Paradoxical","Wake_SD","Sleep_SD","Paradoxical_SD","N_Wake","N_Sleep","N_Paradoxical",
                        "Percent_Wake","Percent_Sleep","Percent_Paradoxical")
}

df_ZT_Mean = cbind(df_ZT_Mean,mean_table)

addWorksheet(wb2, "State - All days")
writeData(wb2,"State - All days", x=df_one)

addWorksheet(wb2, "ZT - Mean")
writeData(wb2,"ZT - Mean", x=df_ZT_Mean)

addWorksheet(wb2, "Phase - All Days")
writeData(wb2, sheet="Phase - All Days", x= df3)

addWorksheet(wb2, "Phase - Mean")
writeData(wb2, sheet="Phase - Mean", x= df_mean_one)

#### Bouts of sleep states #####
bouts_df = RawData
bouts_df$rodent_sleep[bouts_df$rodent_sleep == "P"] = "S"
bouts_df$durations = 0  #new column to store the duration
current_letter <- ""
current_duration <- 0

# Loop through each row and calculate the durations
for (i in 1:(nrow(bouts_df)-1)) {
  if (bouts_df$rodent_sleep[i] != current_letter & bouts_df$rodent_sleep[i+1] != current_letter) {
    current_letter <- bouts_df$rodent_sleep[i]
    current_duration <- 1
  } else {
    current_duration <- current_duration + 1
  }
  
  bouts_df$durations[i] <- current_duration
}

letter_changes <- bouts_df$rodent_sleep[c(TRUE, bouts_df$rodent_sleep[-1] != bouts_df$rodent_sleep[-nrow(bouts_df)])]

# Extract the duration each time the letter changes
duration_changes <- bouts_df$durations[c(which(bouts_df$rodent_sleep %in% letter_changes), nrow(bouts_df))]

for (j in 1:nrow(bouts_df)-1){
  if (bouts_df$durations[j+1]!=1){
    bouts_df$max_dur[j] = NA
  } else {bouts_df$max_dur[j] = bouts_df$durations[j]}
}
bouts_df$max_dur[nrow(bouts_df)] = bouts_df$durations[nrow(bouts_df)]

bouts_df_co = data.frame(bouts_df$date,bouts_df$hour,bouts_df$ZT,bouts_df$rodent_sleep,bouts_df$max_dur)
bouts_df_co = bouts_df_co[complete.cases(bouts_df_co), ]
names(bouts_df_co) = c("Date","Hour","ZT","Sleep_state","Bouts_Duration")
bouts_df_co$'Duration (min)' = bouts_df_co$`Bouts_Duration`*0.16666666666666666666666666666

### Mean by ZT
Bouts_ZT_Mean = data.frame(ZT)
Bouts_mean_table = data.frame()
for (y in ZT){
  Bouts = c(mean(bouts_df_co$'Duration (min)'[bouts_df_co$ZT == y & bouts_df_co$Sleep_state == "W"]),
            sum(bouts_df_co$'Duration (min)'[bouts_df_co$ZT == y & bouts_df_co$Sleep_state == "W"]),
            max(bouts_df_co$'Duration (min)'[bouts_df_co$ZT == y & bouts_df_co$Sleep_state == "W"]),
            sd(bouts_df_co$'Duration (min)'[bouts_df_co$ZT == y & bouts_df_co$Sleep_state == "W"]),
            length(bouts_df_co$'Duration (min)'[bouts_df_co$ZT==y & bouts_df_co$Sleep_state == "W"]),
            mean(bouts_df_co$'Duration (min)'[bouts_df_co$ZT == y & bouts_df_co$Sleep_state == "S"]),
            sum(bouts_df_co$'Duration (min)'[bouts_df_co$ZT == y & bouts_df_co$Sleep_state == "S"]),
            max(bouts_df_co$'Duration (min)'[bouts_df_co$ZT == y & bouts_df_co$Sleep_state == "S"]),
            sd(bouts_df_co$'Duration (min)'[bouts_df_co$ZT == y & bouts_df_co$Sleep_state == "S"]),
            length(bouts_df_co$'Duration (min)'[bouts_df_co$ZT==y & bouts_df_co$Sleep_state == "S"])
  )
  
  Bouts_mean_table = rbind(Bouts_mean_table, Bouts)

  names(Bouts_mean_table) = c("Bouts_W_Mean","Bouts_W_Sum", "Bouts_W_Max","Bouts_W_SD","Bouts_W_n",
                              "Bouts_S_Mean","Bouts_S_Sum","Bouts_S_Max","Bouts_S_SD","Bouts_S_n")
}
Bouts_ZT_Mean = cbind(Bouts_ZT_Mean, Bouts_mean_table)

addWorksheet(wb2, "Bouts - All Days")
writeData(wb2, sheet = "Bouts - All Days" , x=bouts_df_co)

addWorksheet(wb2, "Bouts - ZT - Mean")
writeData(wb2, sheet = "Bouts - ZT - Mean" , x=Bouts_ZT_Mean)

##### onset of sleep at light on
onset_date = data.frame(date)
onset_list = c()
for (t in date){
  Sub_onset = subset(RawData, date == t & ZT == 0)
  if (nrow(Sub_onset != 0)){
     Sub_onset$rodent_sleep[Sub_onset$rodent_sleep == "P"] = "S"
  Sub_onset[,1:2] = NULL
  Sub_onset[,3:17] = NULL
  
  sleep_episode = c()
  for (x in 1:200){
    if (Sub_onset$rodent_sleep[x] == "S" & Sub_onset$rodent_sleep[x+1] == "S" &
        Sub_onset$rodent_sleep[x+2] == "S" ){
      sleep_episode[x]=1
    } else {sleep_episode[x]=0}
  }
  first_sleep = which(sleep_episode == 1)
  onset_sleep = first_sleep[1]*0.166666666666666
   
  } else {onset_sleep = NA}
  onset_list = c(onset_list, onset_sleep)
}
onset_date = cbind(onset_date, onset_list)
names(onset_date) = c("Date", "First_Sleep_30s (min)")
onset_date = na.omit(onset_date)

addWorksheet(wb2, "Bouts - First Sleep")
writeData(wb2, sheet="Bouts - First Sleep", x=onset_date)

#### Loop #####
col=c(names(RawData)[5:11],names(RawData[19]))

for (c in col){
  # c_print = paste0("Analyse of ",c)
  # print(c_print)
  Subset_raw = RawData[,c("date","ZT",c)]
  for (t in date){
    date_ca = rep(t,12)
    Loop_df = data.frame(date_ca,ZT)
    count_table_temp = c()
    for (y in ZT) {
      count_temp = mean(Subset_raw[Subset_raw$ZT == y & Subset_raw$date == t,c])
      count_table_temp = c(count_table_temp, count_temp)
    }
    
    Loop_df = cbind(Loop_df, count_table_temp)
    Temp_sheet = paste0(t,"-", c)
    addWorksheet(wb, Temp_sheet)
    writeData(wb, sheet= Temp_sheet, x = Loop_df)
  }
  Loop_df_one = data.frame()
  for (t in date){
    Temp_sheet = paste0(t,"-",c)
    temp4 = read.xlsx(wb, sheet=Temp_sheet)
    Loop_df_one = rbind(Loop_df_one,temp4)
  }
  
  names(Loop_df_one) = c("Date", "ZT", c)
  
  ### Modif for plot
  x4 = seq(1, length(Loop_df_one$ZT/length(Loop_df_one)))
  Loop_df_one = cbind(Loop_df_one,x4)
  Loop_df_one = na.omit(Loop_df_one)
  
  ### Mean by ZT
  Loop_ZT_Mean = data.frame(ZT)
  Loop_mean_table = data.frame()
  for (y in ZT){
    Loop = c(mean(Loop_df_one[Loop_df_one$ZT == y,c]),
             sd(Loop_df_one[Loop_df_one$ZT == y,c]),
             length(Loop_df_one[Loop_df_one$ZT==y,c])
    )
    
    Loop_mean_table = rbind(Loop_mean_table, Loop)
    names_mean = paste0(c,"_Mean")
    names_SD = paste0(c,"_SD")
    names_n = paste0(c,"_N")
    names(Loop_mean_table) = c(names_mean, names_SD, names_n)
  }
  Loop_ZT_Mean = cbind(Loop_ZT_Mean, Loop_mean_table)
  
  name_All = paste0(c, " - All Days")
  addWorksheet(wb2, name_All)
  writeData(wb2, name_All, x=Loop_df_one)
  
  name_ZT = paste0(c, " - ZT - Mean")
  addWorksheet(wb2, name_ZT)
  writeData(wb2,name_ZT, x=Loop_ZT_Mean)
  
}

# ####### Graphs #######
# a =   ggplot(df_one, aes(x=x-1))+
#       geom_line(aes(y=Wake_percent,color="Wake %"),linewidth=1, na.rm = T)+
#       geom_line(aes(y=Sleep_percent, color="Sleep %"),linewidth=1, na.rm = T)+
#       geom_line(aes(y=Paradoxical_percent,color="Paradoxical %"),linewidth=1, na.rm = T)+
#       geom_point(aes(y=Wake_percent),size=2,shape=3, na.rm = T)+
#       geom_point(aes(y=Sleep_percent),size=2,shape=3, na.rm = T)+      
#       geom_point(aes(y=Paradoxical_percent),size=2,shape=3, na.rm = T)+
#       labs(x='Hours', y='Percentage', title = ID, colour = NULL)+
#       geom_vline(xintercept = h, linetype="dashed")+
#       scale_x_continuous(breaks = seq(0, max(h), by = 4))+
#       theme_classic()
# 
# 
# c = ggplot(df2_one, aes(x=x2-1))+
#        geom_line(aes(y=Wake_ave,color="Wake"),linewidth=1, na.rm = T)+
#        geom_line(aes(y=Sleep_ave, color="Sleep"),linewidth=1, na.rm = T)+
#        geom_line(aes(y=Paradoxical_ave,color="Paradoxical"),linewidth=1, na.rm = T)+
#        geom_point(aes(y=Wake_ave),size=2,shape=3, na.rm = T)+
#        geom_point(aes(y=Sleep_ave),size=2,shape=3, na.rm = T)+      
#        geom_point(aes(y=Paradoxical_ave),size=2,shape=3, na.rm = T)+
#        labs(x='Hours', y='Percentage', title = ID, colour = NULL)+
#        geom_vline(xintercept = h, linetype="dashed")+
#        scale_x_continuous(breaks = seq(0, max(h), by = 4))+
#        theme_classic()
# 
# 
# b = ggplot(df_ZT_Mean, aes(x=ZT))+
#     geom_line(aes(y=Wake,color="Wake"),linewidth=1, na.rm = T)+
#     geom_line(aes(y=Sleep, color="Sleep"),linewidth=1, na.rm = T)+
#     geom_line(aes(y=Paradoxical,color="Paradoxical"),linewidth=1, na.rm = T)+
#     geom_point(aes(y=Wake),size=2,shape=3, na.rm = T)+
#     geom_point(aes(y=Sleep),size=2,shape=3, na.rm = T)+      
#     geom_point(aes(y=Paradoxical),size=2,shape=3, na.rm = T)+
#     geom_errorbar(aes(ymin=Wake-Wake_SD, ymax=Wake+Wake_SD),
#                 width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
#     geom_errorbar(aes(ymin=Sleep-Sleep_SD, ymax=Sleep+Sleep_SD),
#                 width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
#     geom_errorbar(aes(ymin=Paradoxical-Paradoxical_SD, ymax=Paradoxical+Paradoxical_SD),
#                 width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
#     labs(x='ZT', y='Average', title = ID, colour = NULL)+
#     geom_vline(xintercept = 12, linetype="dashed")+
#     scale_x_continuous(breaks = seq(0,22,by=2))+
#     theme_classic()
# 
# d = ggplot(df_mean_one,aes(fill=Phase, x= Stage_sleep, y=Mean_Phase_one))+
#     geom_col(position="dodge",na.rm=T)+
#     geom_errorbar(aes(ymin=Mean_Phase_one-SD_Phase_one, ymax=Mean_Phase_one+SD_Phase_one),
#                 width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
#     theme_classic()+
#     labs(x=NULL, y="Average",title = ID)+
#     geom_hline(yintercept = 0)
# 
# e = ggplot(df3,aes(fill=Date, x= Phase))+
#     geom_col(aes(y=Mean_Wake), position="dodge",na.rm=T)+
#     #geom_errorbar(aes(ymin=Mean_Phase_one-SD_Phase_one, ymax=Mean_Phase_one+SD_Phase_one),
#     #             width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
#     theme_classic()+
#     labs(x=NULL, y="Average",title = "Mean duration of Wake stage")+
#     geom_hline(yintercept = 0)+
#     scale_fill_manual(values = met.brewer("Hokusai1"))
# 
# Temperature_plot =  ggplot(Temperature_df_one, aes(x=x4-1))+
#                     geom_line(aes(y=Temperature),color="blue",linewidth=1, na.rm = T)+
#                     geom_point(aes(y=Temperature),size=2,shape=3, na.rm = T)+
#                     labs(x='Hours', y='Temperature (°C)', title = ID, colour = NULL)+
#                     geom_vline(xintercept = h, linetype="dashed")+
#                     scale_x_continuous(breaks = seq(0, max(h), by = 4))+
#                     theme_classic()
# 
# Temperature_ZT = ggplot(Temperature_ZT_Mean, aes(x=ZT))+
#   geom_line(aes(y=Temperature_Mean),linewidth=1, na.rm = T)+
#   geom_point(aes(y=Temperature_Mean),size=2,shape=3, na.rm = T)+
#   geom_errorbar(aes(ymin=Temperature_Mean-Temperature_SD, ymax=Temperature_Mean+Temperature_SD),
#                 width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
#   labs(x='ZT', y='Mean temperature (°C)', title = ID, colour = NULL)+
#   geom_vline(xintercept = 12, linetype="dashed")+
#   scale_x_continuous(breaks = seq(0,22,by=2))+
#   theme_classic()
# 
# EMG_plot =  ggplot(EMG_df_one, aes(x=x_emg-1))+
#   geom_line(aes(y=EMG),color="green",linewidth=1, na.rm = T)+
#   geom_point(aes(y=EMG),size=2,shape=3, na.rm = T)+
#   labs(x='Hours', y='EMG', title = ID, colour = NULL)+
#   geom_vline(xintercept = h, linetype="dashed")+
#   scale_x_continuous(breaks = seq(0, max(h), by = 4))+
#   theme_classic()
# 
# EMG_ZT = ggplot(EMG_ZT_Mean, aes(x=ZT))+
#   geom_line(aes(y=EMG_Mean),linewidth=1, na.rm = T)+
#   geom_point(aes(y=EMG_Mean),size=2,shape=3, na.rm = T)+
#   geom_errorbar(aes(ymin=EMG_Mean-EMG_SD, ymax=EMG_Mean+EMG_SD),
#                 width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
#   labs(x='ZT', y='Mean EMG', title = ID, colour = NULL)+
#   geom_vline(xintercept = 12, linetype="dashed")+
#   scale_x_continuous(breaks = seq(0,22,by=2))+
#   theme_classic()
# 
# Alpha_plot =  ggplot(Alpha_df_one, aes(x=x_alpha-1))+
#   geom_line(aes(y=Alpha),color="green",linewidth=1, na.rm = T)+
#   geom_point(aes(y=Alpha),size=2,shape=3, na.rm = T)+
#   labs(x='Hours', y='Alpha', title = ID, colour = NULL)+
#   geom_vline(xintercept = h, linetype="dashed")+
#   scale_x_continuous(breaks = seq(0, max(h), by = 4))+
#   theme_classic()
# 
# Alpha_ZT = ggplot(Alpha_ZT_Mean, aes(x=ZT))+
#   geom_line(aes(y=Alpha_Mean),linewidth=1, na.rm = T)+
#   geom_point(aes(y=Alpha_Mean),size=2,shape=3, na.rm = T)+
#   geom_errorbar(aes(ymin=Alpha_Mean-Alpha_SD, ymax=Alpha_Mean+Alpha_SD),
#                 width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
#   labs(x='ZT', y='Mean Alpha', title = ID, colour = NULL)+
#   geom_vline(xintercept = 12, linetype="dashed")+
#   scale_x_continuous(breaks = seq(0,22,by=2))+
#   theme_classic()
# 
# Delta_plot =  ggplot(Delta_df_one, aes(x=x_delta-1))+
#   geom_line(aes(y=Delta),color="green",linewidth=1, na.rm = T)+
#   geom_point(aes(y=Delta),size=2,shape=3, na.rm = T)+
#   labs(x='Hours', y='Delta', title = ID, colour = NULL)+
#   geom_vline(xintercept = h, linetype="dashed")+
#   scale_x_continuous(breaks = seq(0, max(h), by = 4))+
#   theme_classic()
# 
# Delta_ZT = ggplot(Delta_ZT_Mean, aes(x=ZT))+
#   geom_line(aes(y=Delta_Mean),linewidth=1, na.rm = T)+
#   geom_point(aes(y=Delta_Mean),size=2,shape=3, na.rm = T)+
#   geom_errorbar(aes(ymin=Delta_Mean-Delta_SD, ymax=Delta_Mean+Delta_SD),
#                 width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
#   labs(x='ZT', y='Mean Delta', title = ID, colour = NULL)+
#   geom_vline(xintercept = 12, linetype="dashed")+
#   scale_x_continuous(breaks = seq(0,22,by=2))+
#   theme_classic()


#print(a)
#print(c)
#print(b)
#print(d)
#print(e)
#print(Temperature_plot)

#### Output file #####
base_folder = getwd()

if (dir.exists("output")==FALSE){
  dir.create("output")
}
setwd("output")

splits=unlist(data.table::tstrsplit(file_path,"/", fill=NA, type.convert=FALSE, names=F))

exp_name = splits[2]
file_name = paste0(splits[3],"_",splits[2])
if (dir.exists(exp_name)==F){
  dir.create(exp_name)
}

setwd(exp_name)

ID = gsub("/","_", file_path)
filename = paste0(file_name,".xlsx")
saveWorkbook(wb2 , file = filename, overwrite = T)


setwd(base_folder) # Restore main folder
#setwd("C:/Users/hcall/OneDrive/Documents/R/Sleep")
#setwd("E:/R/Sleep")

print(paste0("Successful Analysis of ",ID))
}



Sleep_select = function(criteria){

  crit = as.character(criteria)
  
  crit2=c()
  for (b in crit){
         if (is_empty(crit2)){
               crit2 = paste0(b)
           } else {crit2=paste0(crit2,".+",b)
           }
  }
  
  base_folder = getwd()
  setwd("input")
  a_unique = unique(dirname(list.files(pattern = crit2, recursive = T, ignore.case = T))) #Change the pattern to choose more precisely an experiment, a mouse ID, etc.
                                                                                          # To use multiple arguments, use pattern = "arg1.+arg2+arg3"
                                                                                          # WARNING: Arguments should be in the same order as in the file name.
                                                                                          # It can take a while if there is a lot of recordings to analyze
  setwd(base_folder)
  for (a in a_unique){
    a2 = paste0("input/",a)
    Sleep_analysis(a2)
  }
}

######## Test zone, please ignore
# commands <- list(
#   'o' = over,
#   'b' = over,
#   'u' = over,
#   'p' = point,
#   'l' = length,
#   'v' = volume,
#   'n' = name,
#   'e' = name
# )
# 
# func <- commands[[args$command]]
# if (!is.null(func)) {
#   func()
# } else {
#   print('WRONG ARGUMENT, try again or check the help (-h)')
# }