###TODO
### Autosave figures?
### Made as a function......

######### Required package ##########
if(!require(tidyr)){install.packages("tidyr")}
if(!require(openxlsx)){install.packages("openxlsx")}
if(!require(ggplot2)){install.packages("ggplot2")}
if(!require(tidyverse)){install.packages("tidyverse")}
if(!require(MetBrewer)){install.packages("MetBrewer")}

###### Data Import and preparation #####
### Import dataframe generated by importing all .csv files in a given folder
RawData = list.files(path = "./3086/", pattern = "*.csv", full.names = T) %>% map_df(~read.csv(.))
ID = 3086

### Separate date and time
RawData = separate(RawData,time_stamp, into = c("date","hour"),sep=" ")
RawData = arrange(RawData, date, idx)
date = unique(RawData$date)

# Base parameters
ZT = seq(0,22, by=2)
wb = createWorkbook()
wb2 = createWorkbook()
State = c("W", "S", "P")


#### Sleep state extraction ####
for (t in date){
  Subfull = subset(RawData, date == t)
  date_ca = rep(t,12)
  df = data.frame(date_ca,ZT) #Reset the dataframe at each loop
  df2 = data.frame(date_ca,ZT)
  for (z in State){
    count_table = c() #reset the array at each loop
    count_table_max = c()
    count_table_mean = c()
    for (y in ZT){
      count <- nrow(Subfull[Subfull$ZT == y & Subfull$rodent_sleep == z,])
      count_table = c(count_table, count)
      
      ### Count of sequential same state
      sub_Subfull = subset(Subfull, ZT == y)
      if (length(sub_Subfull$ZT !=0)){
      r = rle(sub_Subfull$rodent_sleep == z)
      count_ser = r$lengths[r$values == TRUE]
      max_count = max(count_ser)
      ave_count = mean(count_ser)
      } else {
        max_count = NA
        ave_count = NA
      }

      ### Conbine all ZT
      count_table_max = c(count_table_max, max_count)
      count_table_mean = c(count_table_mean, ave_count)
    }
    df = cbind(df, count_table)
    df2 = cbind(df2, count_table_max,count_table_mean)
  }
  
  names(df)=c("Date","ZT", "Wake", "Sleep", "Paradoxical")
  names(df2)=c("Date","ZT", "Wake_max", "Wake_ave", "Sleep_max", "Sleep_ave",
               "Paradoxical_max", "Paradoxical_ave")
  
  ### Create sum and percentage columns
  df$Sum = df$Wake + df$Sleep + df$Paradoxical
  df$Wake_percent = df$Wake / df$Sum * 100
  df$Sleep_percent = df$Sleep / df$Sum * 100
  df$Paradoxical_percent = df$Paradoxical / df$Sum * 100
  
  ### Create dataframe for summary of state per phase
  Phase = c(rep("Light",3),rep("Dark",3))
  Stage_sleep = rep(c("Wake","Sleep","Paradoxical"),2)
  Sum_Phase = c(sum(df[1:6,3]),sum(df[1:6,4]),sum(df[1:6,5]),sum(df[7:12,3]),
                sum(df[7:12,4]),sum(df[7:12,5]))
  df_sum = data.frame(Phase, Stage_sleep,Sum_Phase)
  
  Mean_Phase = c(mean(df[1:6,3]),mean(df[1:6,4]),mean(df[1:6,5]),mean(df[7:12,3]),
                 mean(df[7:12,4]),mean(df[7:12,5]))
  df_mean = data.frame(Phase, Stage_sleep, Mean_Phase)

  ### add data to workbook
  addWorksheet(wb, t)
  writeData(wb, sheet= t, x = df)
  
  alt_title = paste0(t,"-summary")
  addWorksheet(wb, alt_title)
  writeData(wb, sheet = alt_title, x=df_sum)
  
  df2_name = paste0(t,"-bouts")
  addWorksheet(wb,df2_name)
  writeData(wb, sheet = df2_name, x= df2)
}

### Combine all days
df_one = data.frame()
for (t in date){
  temp = read.xlsx(wb, sheet=t)
  df_one = rbind(df_one,temp)
}
x = seq(1, length(df_one$Wake/length(df_one)))
h = seq(0, length(df_one$ZT), by=12)
df_one = cbind(df_one,x)
df_one = df_one[df_one$Sum != 0,]

df2_one = data.frame()
for (t in date){
  df2_name = paste0(t,"-bouts")
  temp2 = read.xlsx(wb, sheet=df2_name)
  df2_one = rbind(df2_one,temp2)
}

x2 = seq(1, length(df2_one$Wake_max/length(df2_one)))
df2_one = cbind(df2_one,x2)
df2_one = na.omit(df2_one)

### Create dataframe for summary of state per phase
Phase = c(rep("Light",3),rep("Dark",3))
Stage_sleep = rep(c("Wake","Sleep","Paradoxical"),2)

Mean_Phase_one = c(mean(df_one$Wake[df_one$ZT < 12]),mean(df_one$Sleep[df_one$ZT < 12]),mean(df_one$Paradoxical[df_one$ZT < 12]),
                   mean(df_one$Wake[df_one$ZT >= 12]),mean(df_one$Sleep[df_one$ZT >= 12]),mean(df_one$Paradoxical[df_one$ZT >= 12]))

SEM_Phase_one = c(sd(df_one$Wake[df_one$ZT < 12])/length(df_one$Wake[df_one$ZT < 12]),
                  sd(df_one$Sleep[df_one$ZT < 12])/length(df_one$Sleep[df_one$ZT < 12]),
                  sd(df_one$Paradoxical[df_one$ZT < 12])/length(df_one$Paradoxical[df_one$ZT < 12]),
                  sd(df_one$Wake[df_one$ZT >= 12])/length(df_one$Wake[df_one$ZT >= 12]),
                  sd(df_one$Sleep[df_one$ZT >= 12])/length(df_one$Sleep[df_one$ZT >= 12]),
                  sd(df_one$Paradoxical[df_one$ZT >= 12])/length(df_one$Paradoxical[df_one$ZT >= 12])
                  )
df_mean_one = data.frame(Phase, Stage_sleep, Mean_Phase_one, SEM_Phase_one)

date_phase= c(date,date)
date_phase = sort(date_phase)
Phase_day = rep(c("Light","Dark"),length(date_phase)/2)
df3 = data.frame(date_phase, Phase_day)
df3_gne = data.frame()
temp_df3 = c()

for (t in date){
  Mean_Light_day = c(mean(df_one$Wake[df_one$ZT<12 & df_one$Date ==t]),
                     mean(df_one$Sleep[df_one$ZT<12 & df_one$Date ==t]),
                     mean(df_one$Paradoxical[df_one$ZT<12 & df_one$Date ==t]),
                     sd(df_one$Wake[df_one$ZT<12 & df_one$Date ==t])/length(df_one$Wake[df_one$ZT<12 & df_one$Date ==t]),
                     sd(df_one$Sleep[df_one$ZT<12 & df_one$Date ==t])/length(df_one$Sleep[df_one$ZT<12 & df_one$Date ==t]),
                     sd(df_one$Paradoxical[df_one$ZT<12 & df_one$Date ==t])/length(df_one$Paradoxical[df_one$ZT<12 & df_one$Date ==t]))
  
  Mean_Dark_day = c(mean(df_one$Wake[df_one$ZT>=12 & df_one$Date ==t]),
                     mean(df_one$Sleep[df_one$ZT>=12 & df_one$Date ==t]),
                     mean(df_one$Paradoxical[df_one$ZT<12 & df_one$Date ==t]),
                     sd(df_one$Wake[df_one$ZT>=12&df_one$Date ==t])/length(df_one$Wake[df_one$ZT>=12&df_one$Date ==t]),
                     sd(df_one$Sleep[df_one$ZT>=12&df_one$Date ==t])/length(df_one$Sleep[df_one$ZT>=12&df_one$Date ==t]),
                     sd(df_one$Paradoxical[df_one$ZT>=12&df_one$Date ==t])/length(df_one$Paradoxical[df_one$ZT>=12&df_one$Date ==t]))

  temp_df3 = rbind(temp_df3, Mean_Light_day,Mean_Dark_day)
}
df3 = cbind(df3,temp_df3)
names(df3) = c("Date","Phase","Mean_Wake","Mean_Sleep","Mean_Paradoxical","SEM_Wake","SEM_Sleep","SEM_Paradoxical")
rownames(df3)=NULL
df3 = df3[df3$Mean_Wake !=0,]

df_ZT_Mean = data.frame(ZT)
mean_table = data.frame()
for (y in ZT){
  ZT_mean = c(mean(df_one$Wake[df_one$ZT == y]),mean(df_one$Sleep[df_one$ZT == y]),mean(df_one$Paradoxical[df_one$ZT == y]),
              sd(df_one$Wake[df_one$ZT ==y])/length(df_one$Wake[df_one$ZT == y]),
              sd(df_one$Sleep[df_one$ZT ==y])/length(df_one$Sleep[df_one$ZT==y]),
              sd(df_one$Paradoxical[df_one$ZT ==y])/length(df_one$Paradoxical[df_one$ZT==y])
              )
  
  mean_table = rbind(mean_table, ZT_mean)
  names(mean_table) = c("Wake","Sleep","Paradoxical","Wake_SEM","Sleep_SEM","Paradoxical_SEM")
}

df_ZT_Mean = cbind(df_ZT_Mean,mean_table)

###### Temperature ######

for (t in date){
  date_ca = rep(t,12)
  Temperature_df = data.frame(date_ca,ZT)
  count_table_temp = c()
  for (y in ZT) {
    count_temp = mean(RawData$Temp[RawData$ZT == y & RawData$date == t])
    count_table_temp = c(count_table_temp, count_temp)
  }
  
  Temperature_df = cbind(Temperature_df, count_table_temp)
  Temp_sheet = paste0(t,"-Temperature")
  addWorksheet(wb, Temp_sheet)
  writeData(wb, sheet= Temp_sheet, x = Temperature_df)
}
Temperature_df_one = data.frame()
for (t in date){
  Temp_sheet = paste0(t,"-Temperature")
  temp4 = read.xlsx(wb, sheet=Temp_sheet)
  Temperature_df_one = rbind(Temperature_df_one,temp4)
}
names(Temperature_df_one) = c("Date", "ZT", "Temperature")

### Modif for plot
x4 = seq(1, length(Temperature_df_one$ZT/length(Temperature_df_one)))
Temperature_df_one = cbind(Temperature_df_one,x4)
Temperature_df_one = na.omit(Temperature_df_one)

### Mean by ZT
Temperature_ZT_Mean = data.frame(ZT)
Temperature_mean_table = data.frame()
for (y in ZT){
  Temperature = c(mean(Temperature_df_one$Temperature[Temperature_df_one$ZT == y]),
                        sd(Temperature_df_one$Temperature[Temperature_df_one$ZT == y])
                        /length(Temperature_df_one$Temperature[Temperature_df_one$ZT==y])
                        )
  
  Temperature_mean_table = rbind(Temperature_mean_table, Temperature)
  names(Temperature_mean_table) = c("Temperature_Mean","Temperature_SEM")
}

Temperature_ZT_Mean = cbind(Temperature_ZT_Mean, Temperature_mean_table)

###### EMG ######

for (t in date){
  date_ca = rep(t,12)
  EMG_df = data.frame(date_ca,ZT)
  count_table_emg = c()
  
  for (y in ZT) {
    count_emg = mean(RawData$EMG_z[RawData$ZT == y & RawData$date == t])
    count_table_emg = c(count_table_emg, count_emg)
  }
  
  EMG_df = cbind(EMG_df, count_table_emg)
  
  EMG_sheet = paste0(t,"-EMG")
  addWorksheet(wb, EMG_sheet)
  writeData(wb, sheet= EMG_sheet, x = EMG_df)
}
EMG_df_one = data.frame()
for (t in date){
  EMG_sheet = paste0(t,"-EMG")
  emg = read.xlsx(wb, sheet=EMG_sheet)
  EMG_df_one = rbind(EMG_df_one,emg)
}
names(EMG_df_one) = c("Date", "ZT", "EMG")

### Modif for plot
x_emg = seq(1, length(EMG_df_one$ZT/length(EMG_df_one)))
EMG_df_one = cbind(EMG_df_one,x_emg)
EMG_df_one = na.omit(EMG_df_one)

### Mean by ZT
EMG_ZT_Mean = data.frame(ZT)
EMG_mean_table = data.frame()
for (y in ZT){
  EMG = c(mean(EMG_df_one$EMG[EMG_df_one$ZT == y]),
                  sd(EMG_df_one$EMG[EMG_df_one$ZT == y])
                  /length(EMG_df_one$EMG[EMG_df_one$ZT==y])
  )
  
  EMG_mean_table = rbind(EMG_mean_table, EMG)
  names(EMG_mean_table) = c("EMG_Mean","EMG_SEM")
}

EMG_ZT_Mean = cbind(EMG_ZT_Mean, EMG_mean_table)

###### Alpha ######

for (t in date){
  date_ca = rep(t,12)
  Alpha_df = data.frame(date_ca,ZT)
  count_table_alpha = c()
  
  for (y in ZT) {
    count_alpha = mean(RawData$Alpha_z[RawData$ZT == y & RawData$date == t])
    count_table_alpha = c(count_table_alpha, count_alpha)
  }
  
  Alpha_df = cbind(Alpha_df, count_table_alpha)
  
  Alpha_sheet = paste0(t,"-Alpha")
  addWorksheet(wb, Alpha_sheet)
  writeData(wb, sheet= Alpha_sheet, x = Alpha_df)
}
Alpha_df_one = data.frame()
for (t in date){
  Alpha_sheet = paste0(t,"-Alpha")
  alpha = read.xlsx(wb, sheet=Alpha_sheet)
  Alpha_df_one = rbind(Alpha_df_one,alpha)
}
names(Alpha_df_one) = c("Date", "ZT", "Alpha")

### Modif for plot
x_alpha = seq(1, length(Alpha_df_one$ZT/length(Alpha_df_one)))
Alpha_df_one = cbind(Alpha_df_one,x_alpha)
Alpha_df_one = na.omit(Alpha_df_one)

### Mean by ZT
Alpha_ZT_Mean = data.frame(ZT)
Alpha_mean_table = data.frame()
for (y in ZT){
  Alpha = c(mean(Alpha_df_one$Alpha[Alpha_df_one$ZT == y]),
          sd(Alpha_df_one$Alpha[Alpha_df_one$ZT == y])
          /length(Alpha_df_one$Alpha[Alpha_df_one$ZT==y])
  )
  
  Alpha_mean_table = rbind(Alpha_mean_table, Alpha)
  names(Alpha_mean_table) = c("Alpha_Mean","Alpha_SEM")
}

Alpha_ZT_Mean = cbind(Alpha_ZT_Mean, Alpha_mean_table)

###### Beta ######

for (t in date){
  date_ca = rep(t,12)
  Beta_df = data.frame(date_ca,ZT)
  count_table_Beta = c()
  
  for (y in ZT) {
    count_Beta = mean(RawData$Beta_z[RawData$ZT == y & RawData$date == t])
    count_table_Beta = c(count_table_Beta, count_Beta)
  }
  
  Beta_df = cbind(Beta_df, count_table_Beta)
  
  Beta_sheet = paste0(t,"-Beta")
  addWorksheet(wb, Beta_sheet)
  writeData(wb, sheet= Beta_sheet, x = Beta_df)
}
Beta_df_one = data.frame()
for (t in date){
  Beta_sheet = paste0(t,"-Beta")
  Beta = read.xlsx(wb, sheet=Beta_sheet)
  Beta_df_one = rbind(Beta_df_one,Beta)
}
names(Beta_df_one) = c("Date", "ZT", "Beta")

### Modif for plot
x_Beta = seq(1, length(Beta_df_one$ZT/length(Beta_df_one)))
Beta_df_one = cbind(Beta_df_one,x_Beta)
Beta_df_one = na.omit(Beta_df_one)

### Mean by ZT
Beta_ZT_Mean = data.frame(ZT)
Beta_mean_table = data.frame()
for (y in ZT){
  Beta = c(mean(Beta_df_one$Beta[Beta_df_one$ZT == y]),
            sd(Beta_df_one$Beta[Beta_df_one$ZT == y])
            /length(Beta_df_one$Beta[Beta_df_one$ZT==y])
  )
  
  Beta_mean_table = rbind(Beta_mean_table, Beta)
  names(Beta_mean_table) = c("Beta_Mean","Beta_SEM")
}

Beta_ZT_Mean = cbind(Beta_ZT_Mean, Beta_mean_table)

###### Delta ######

for (t in date){
  date_ca = rep(t,12)
  Delta_df = data.frame(date_ca,ZT)
  count_table_delta = c()
  
  for (y in ZT) {
    count_delta = mean(RawData$Delta_z[RawData$ZT == y & RawData$date == t])
    count_table_delta = c(count_table_delta, count_delta)
  }
  
  Delta_df = cbind(Delta_df, count_table_delta)
  
  Delta_sheet = paste0(t,"-Delta")
  addWorksheet(wb, Delta_sheet)
  writeData(wb, sheet= Delta_sheet, x = Delta_df)
}
Delta_df_one = data.frame()
for (t in date){
  Delta_sheet = paste0(t,"-Delta")
  delta = read.xlsx(wb, sheet=Delta_sheet)
  Delta_df_one = rbind(Delta_df_one,delta)
}
names(Delta_df_one) = c("Date", "ZT", "Delta")

### Modif for plot
x_delta = seq(1, length(Delta_df_one$ZT/length(Delta_df_one)))
Delta_df_one = cbind(Delta_df_one,x_delta)
Delta_df_one = na.omit(Delta_df_one)

### Mean by ZT
Delta_ZT_Mean = data.frame(ZT)
Delta_mean_table = data.frame()
for (y in ZT){
  Delta = c(mean(Delta_df_one$Delta[Delta_df_one$ZT == y]),
            sd(Delta_df_one$Delta[Delta_df_one$ZT == y])
            /length(Delta_df_one$Delta[Delta_df_one$ZT==y])
  )
  
  Delta_mean_table = rbind(Delta_mean_table, Delta)
  names(Delta_mean_table) = c("Delta_Mean","Delta_SEM")
}

Delta_ZT_Mean = cbind(Delta_ZT_Mean, Delta_mean_table)

###### Sigma ######

for (t in date){
  date_ca = rep(t,12)
  Sigma_df = data.frame(date_ca,ZT)
  count_table_Sigma = c()
  
  for (y in ZT) {
    count_Sigma = mean(RawData$Sigma_z[RawData$ZT == y & RawData$date == t])
    count_table_Sigma = c(count_table_Sigma, count_Sigma)
  }
  
  Sigma_df = cbind(Sigma_df, count_table_Sigma)
  
  Sigma_sheet = paste0(t,"-Sigma")
  addWorksheet(wb, Sigma_sheet)
  writeData(wb, sheet= Sigma_sheet, x = Sigma_df)
}
Sigma_df_one = data.frame()
for (t in date){
  Sigma_sheet = paste0(t,"-Sigma")
  Sigma = read.xlsx(wb, sheet=Sigma_sheet)
  Sigma_df_one = rbind(Sigma_df_one,Sigma)
}
names(Sigma_df_one) = c("Date", "ZT", "Sigma")

### Modif for plot
x_Sigma = seq(1, length(Sigma_df_one$ZT/length(Sigma_df_one)))
Sigma_df_one = cbind(Sigma_df_one,x_Sigma)
Sigma_df_one = na.omit(Sigma_df_one)

### Mean by ZT
Sigma_ZT_Mean = data.frame(ZT)
Sigma_mean_table = data.frame()
for (y in ZT){
  Sigma = c(mean(Sigma_df_one$Sigma[Sigma_df_one$ZT == y]),
            sd(Sigma_df_one$Sigma[Sigma_df_one$ZT == y])
            /length(Sigma_df_one$Sigma[Sigma_df_one$ZT==y])
  )
  
  Sigma_mean_table = rbind(Sigma_mean_table, Sigma)
  names(Sigma_mean_table) = c("Sigma_Mean","Sigma_SEM")
}

Sigma_ZT_Mean = cbind(Sigma_ZT_Mean, Sigma_mean_table)

###### Theta ######

for (t in date){
  date_ca = rep(t,12)
  Theta_df = data.frame(date_ca,ZT)
  count_table_Theta = c()
  
  for (y in ZT) {
    count_Theta = mean(RawData$Theta_z[RawData$ZT == y & RawData$date == t])
    count_table_Theta = c(count_table_Theta, count_Theta)
  }
  
  Theta_df = cbind(Theta_df, count_table_Theta)
  
  Theta_sheet = paste0(t,"-Theta")
  addWorksheet(wb, Theta_sheet)
  writeData(wb, sheet= Theta_sheet, x = Theta_df)
}
Theta_df_one = data.frame()
for (t in date){
  Theta_sheet = paste0(t,"-Theta")
  Theta = read.xlsx(wb, sheet=Theta_sheet)
  Theta_df_one = rbind(Theta_df_one,Theta)
}
names(Theta_df_one) = c("Date", "ZT", "Theta")

### Modif for plot
x_Theta = seq(1, length(Theta_df_one$ZT/length(Theta_df_one)))
Theta_df_one = cbind(Theta_df_one,x_Theta)
Theta_df_one = na.omit(Theta_df_one)

### Mean by ZT
Theta_ZT_Mean = data.frame(ZT)
Theta_mean_table = data.frame()
for (y in ZT){
  Theta = c(mean(Theta_df_one$Theta[Theta_df_one$ZT == y]),
            sd(Theta_df_one$Theta[Theta_df_one$ZT == y])
            /length(Theta_df_one$Theta[Theta_df_one$ZT==y])
  )
  
  Theta_mean_table = rbind(Theta_mean_table, Theta)
  names(Theta_mean_table) = c("Theta_Mean","Theta_SEM")
}

Theta_ZT_Mean = cbind(Theta_ZT_Mean, Theta_mean_table)

####### Graphs #######
a =   ggplot(df_one, aes(x=x-1))+
      geom_line(aes(y=Wake_percent,color="Wake %"),linewidth=1, na.rm = T)+
      geom_line(aes(y=Sleep_percent, color="Sleep %"),linewidth=1, na.rm = T)+
      geom_line(aes(y=Paradoxical_percent,color="Paradoxical %"),linewidth=1, na.rm = T)+
      geom_point(aes(y=Wake_percent),size=2,shape=3, na.rm = T)+
      geom_point(aes(y=Sleep_percent),size=2,shape=3, na.rm = T)+      
      geom_point(aes(y=Paradoxical_percent),size=2,shape=3, na.rm = T)+
      labs(x='Hours', y='Percentage', title = ID, colour = NULL)+
      geom_vline(xintercept = h, linetype="dashed")+
      scale_x_continuous(breaks = seq(0, max(h), by = 4))+
      theme_classic()


c = ggplot(df2_one, aes(x=x2-1))+
       geom_line(aes(y=Wake_ave,color="Wake"),linewidth=1, na.rm = T)+
       geom_line(aes(y=Sleep_ave, color="Sleep"),linewidth=1, na.rm = T)+
       geom_line(aes(y=Paradoxical_ave,color="Paradoxical"),linewidth=1, na.rm = T)+
       geom_point(aes(y=Wake_ave),size=2,shape=3, na.rm = T)+
       geom_point(aes(y=Sleep_ave),size=2,shape=3, na.rm = T)+      
       geom_point(aes(y=Paradoxical_ave),size=2,shape=3, na.rm = T)+
       labs(x='Hours', y='Percentage', title = ID, colour = NULL)+
       geom_vline(xintercept = h, linetype="dashed")+
       scale_x_continuous(breaks = seq(0, max(h), by = 4))+
       theme_classic()


b = ggplot(df_ZT_Mean, aes(x=ZT))+
    geom_line(aes(y=Wake,color="Wake"),linewidth=1, na.rm = T)+
    geom_line(aes(y=Sleep, color="Sleep"),linewidth=1, na.rm = T)+
    geom_line(aes(y=Paradoxical,color="Paradoxical"),linewidth=1, na.rm = T)+
    geom_point(aes(y=Wake),size=2,shape=3, na.rm = T)+
    geom_point(aes(y=Sleep),size=2,shape=3, na.rm = T)+      
    geom_point(aes(y=Paradoxical),size=2,shape=3, na.rm = T)+
    geom_errorbar(aes(ymin=Wake-Wake_SEM, ymax=Wake+Wake_SEM),
                width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
    geom_errorbar(aes(ymin=Sleep-Sleep_SEM, ymax=Sleep+Sleep_SEM),
                width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
    geom_errorbar(aes(ymin=Paradoxical-Paradoxical_SEM, ymax=Paradoxical+Paradoxical_SEM),
                width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
    labs(x='ZT', y='Average', title = ID, colour = NULL)+
    geom_vline(xintercept = 12, linetype="dashed")+
    scale_x_continuous(breaks = seq(0,22,by=2))+
    theme_classic()

d = ggplot(df_mean_one,aes(fill=Phase, x= Stage_sleep, y=Mean_Phase_one))+
    geom_col(position="dodge",na.rm=T)+
    geom_errorbar(aes(ymin=Mean_Phase_one-SEM_Phase_one, ymax=Mean_Phase_one+SEM_Phase_one),
                width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
    theme_classic()+
    labs(x=NULL, y="Average",title = ID)+
    geom_hline(yintercept = 0)

e = ggplot(df3,aes(fill=Date, x= Phase))+
    geom_col(aes(y=Mean_Wake), position="dodge",na.rm=T)+
    #geom_errorbar(aes(ymin=Mean_Phase_one-SEM_Phase_one, ymax=Mean_Phase_one+SEM_Phase_one),
    #             width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
    theme_classic()+
    labs(x=NULL, y="Average",title = "Mean duration of Wake stage")+
    geom_hline(yintercept = 0)+
    scale_fill_manual(values = met.brewer("Hokusai1"))

Temperature_plot =  ggplot(Temperature_df_one, aes(x=x4-1))+
                    geom_line(aes(y=Temperature),color="blue",linewidth=1, na.rm = T)+
                    geom_point(aes(y=Temperature),size=2,shape=3, na.rm = T)+
                    labs(x='Hours', y='Temperature (°C)', title = ID, colour = NULL)+
                    geom_vline(xintercept = h, linetype="dashed")+
                    scale_x_continuous(breaks = seq(0, max(h), by = 4))+
                    theme_classic()

Temperature_ZT = ggplot(Temperature_ZT_Mean, aes(x=ZT))+
  geom_line(aes(y=Temperature_Mean),linewidth=1, na.rm = T)+
  geom_point(aes(y=Temperature_Mean),size=2,shape=3, na.rm = T)+
  geom_errorbar(aes(ymin=Temperature_Mean-Temperature_SEM, ymax=Temperature_Mean+Temperature_SEM),
                width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
  labs(x='ZT', y='Mean temperature (°C)', title = ID, colour = NULL)+
  geom_vline(xintercept = 12, linetype="dashed")+
  scale_x_continuous(breaks = seq(0,22,by=2))+
  theme_classic()

EMG_plot =  ggplot(EMG_df_one, aes(x=x_emg-1))+
  geom_line(aes(y=EMG),color="green",linewidth=1, na.rm = T)+
  geom_point(aes(y=EMG),size=2,shape=3, na.rm = T)+
  labs(x='Hours', y='EMG', title = ID, colour = NULL)+
  geom_vline(xintercept = h, linetype="dashed")+
  scale_x_continuous(breaks = seq(0, max(h), by = 4))+
  theme_classic()

EMG_ZT = ggplot(EMG_ZT_Mean, aes(x=ZT))+
  geom_line(aes(y=EMG_Mean),linewidth=1, na.rm = T)+
  geom_point(aes(y=EMG_Mean),size=2,shape=3, na.rm = T)+
  geom_errorbar(aes(ymin=EMG_Mean-EMG_SEM, ymax=EMG_Mean+EMG_SEM),
                width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
  labs(x='ZT', y='Mean EMG', title = ID, colour = NULL)+
  geom_vline(xintercept = 12, linetype="dashed")+
  scale_x_continuous(breaks = seq(0,22,by=2))+
  theme_classic()

Alpha_plot =  ggplot(Alpha_df_one, aes(x=x_alpha-1))+
  geom_line(aes(y=Alpha),color="green",linewidth=1, na.rm = T)+
  geom_point(aes(y=Alpha),size=2,shape=3, na.rm = T)+
  labs(x='Hours', y='Alpha', title = ID, colour = NULL)+
  geom_vline(xintercept = h, linetype="dashed")+
  scale_x_continuous(breaks = seq(0, max(h), by = 4))+
  theme_classic()

Alpha_ZT = ggplot(Alpha_ZT_Mean, aes(x=ZT))+
  geom_line(aes(y=Alpha_Mean),linewidth=1, na.rm = T)+
  geom_point(aes(y=Alpha_Mean),size=2,shape=3, na.rm = T)+
  geom_errorbar(aes(ymin=Alpha_Mean-Alpha_SEM, ymax=Alpha_Mean+Alpha_SEM),
                width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
  labs(x='ZT', y='Mean Alpha', title = ID, colour = NULL)+
  geom_vline(xintercept = 12, linetype="dashed")+
  scale_x_continuous(breaks = seq(0,22,by=2))+
  theme_classic()

Delta_plot =  ggplot(Delta_df_one, aes(x=x_delta-1))+
  geom_line(aes(y=Delta),color="green",linewidth=1, na.rm = T)+
  geom_point(aes(y=Delta),size=2,shape=3, na.rm = T)+
  labs(x='Hours', y='Delta', title = ID, colour = NULL)+
  geom_vline(xintercept = h, linetype="dashed")+
  scale_x_continuous(breaks = seq(0, max(h), by = 4))+
  theme_classic()

Delta_ZT = ggplot(Delta_ZT_Mean, aes(x=ZT))+
  geom_line(aes(y=Delta_Mean),linewidth=1, na.rm = T)+
  geom_point(aes(y=Delta_Mean),size=2,shape=3, na.rm = T)+
  geom_errorbar(aes(ymin=Delta_Mean-Delta_SEM, ymax=Delta_Mean+Delta_SEM),
                width=0.25, colour='black', linewidth = 0.75,position = "dodge")+
  labs(x='ZT', y='Mean Delta', title = ID, colour = NULL)+
  geom_vline(xintercept = 12, linetype="dashed")+
  scale_x_continuous(breaks = seq(0,22,by=2))+
  theme_classic()


#print(a)
#print(c)
#print(b)
#print(d)
#print(e)
#print(Temperature_plot)

#### Output file #####

addWorksheet(wb2, "ZT - All days")
writeData(wb2, sheet= "ZT - All days", x= df_one)

addWorksheet(wb2, "ZT - Mean")
writeData(wb2,"ZT - Mean", x=df_ZT_Mean)

addWorksheet(wb2, "Phase - All Days")
writeData(wb2, sheet="Phase - All Days", x= df3)

addWorksheet(wb2, "Phase - Mean")
writeData(wb2, sheet="Phase - Mean", x= df_mean_one)

addWorksheet(wb2, "Temperature - All days")
writeData(wb2, "Temperature - All days", x=Temperature_df_one)

filename = paste0(ID,".xlsx")
saveWorkbook(wb2 , file = filename, overwrite = T)

